# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sounds',
            old_name='sounds',
            new_name='files',
        ),
        migrations.AddField(
            model_name='sounds',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
