# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170614_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sounds',
            new_name='Sound',
        ),
    ]
